# Lista COCA – najczęstsze słowa angielskie z tłumaczeniami PL
# Format: (słowo, tłumaczenie_pl, rank)

COCA_WORDS = [
    ("ability","zdolność",1),("absence","nieobecność",2),("absolute","absolutny",3),
    ("accept","akceptować",4),("access","dostęp",5),("account","konto; kwestia",6),
    ("achieve","osiągnąć",7),("acknowledge","uznać; przyznać",8),("acquire","nabyć",9),
    ("action","działanie",10),("adapt","dostosować się",11),("address","adres; mowa",12),
    ("adequate","wystarczający",13),("adjust","dostosować",14),("admit","przyznać",15),
    ("adopt","przyjąć; zaadoptować",16),("advance","postęp; awans",17),
    ("advantage","zaleta; przewaga",18),("affect","wpływać na",19),
    ("afford","pozwolić sobie",20),("agency","agencja",21),("agree","zgadzać się",22),
    ("alert","alert; czujny",23),("allow","pozwolić",24),("alter","zmienić",25),
    ("alternative","alternatywa",26),("although","chociaż",27),("announce","ogłaszać",28),
    ("answer","odpowiedź",29),("anxiety","niepokój",30),("apart","oddzielnie",31),
    ("apply","aplikować; stosować",32),("approach","podejście",33),
    ("appropriate","odpowiedni",34),("approve","zatwierdzić",35),("argue","kłócić się; twierdzić",36),
    ("arise","pojawić się",37),("aspect","aspekt",38),("assess","oceniać",39),
    ("assist","pomagać",40),("assume","zakładać",41),("assumption","założenie",42),
    ("attach","dołączyć",43),("attempt","próba; usiłować",44),("attitude","postawa",45),
    ("attract","przyciągać",46),("authority","władza; autorytet",47),("aware","świadomy",48),
    ("basis","podstawa",49),("behavior","zachowanie",50),("benefit","korzyść",51),
    ("blame","winić; wina",52),("border","granica",53),("brief","krótki; skrótowy",54),
    ("broadly","ogólnie",55),("capability","zdolność; możliwość",56),
    ("capture","uchwycić; przechwycić",57),("challenge","wyzwanie",58),
    ("characteristic","cecha charakterystyczna",59),("choice","wybór",60),
    ("circumstance","okoliczność",61),("claim","twierdzić; roszczenie",62),
    ("combine","łączyć",63),("comment","komentarz",64),("commitment","zobowiązanie",65),
    ("community","społeczność",66),("complex","złożony",67),("concern","obawa; dotyczyć",68),
    ("confidence","pewność siebie",69),("conflict","konflikt",70),
    ("consequence","konsekwencja",71),("consider","rozważać",72),
    ("consideration","rozwaga; wzgląd",73),("consistent","konsekwentny; spójny",74),
    ("contribute","przyczyniać się",75),("contribution","wkład",76),
    ("convince","przekonać",77),("crucial","kluczowy",78),("debate","debata",79),
    ("decline","spadek; odrzucić",80),("define","definiować",81),("deliver","dostarczyć",82),
    ("demand","popyt; żądać",83),("demonstrate","demonstrować",84),
    ("depend","zależeć",85),("derive","wywodzić się",86),("describe","opisać",87),
    ("detail","szczegół",88),("determine","określać; ustalać",89),
    ("develop","rozwijać",90),("difference","różnica",91),("difficult","trudny",92),
    ("distinct","odrębny; wyraźny",93),("doubt","wątpliwość",94),("dozen","tuzin",95),
    ("drive","napędzać; jechać",96),("dynamic","dynamiczny",97),("effective","skuteczny",98),
    ("effort","wysiłek",99),("emerge","pojawić się; wyłonić się",100),
    ("emphasis","nacisk; podkreślenie",101),("enable","umożliwiać",102),
    ("enhance","ulepszyć; wzmocnić",103),("ensure","zapewnić",104),
    ("equal","równy",105),("establish","ustanawiać; zakładać",106),
    ("estimate","szacować; szacunek",107),("evaluate","oceniać",108),
    ("eventually","ostatecznie; w końcu",109),("evidence","dowód",110),
    ("examine","badać; sprawdzać",111),("exist","istnieć",112),("expand","rozszerzać",113),
    ("expect","oczekiwać",114),("expense","wydatek",115),("explain","wyjaśnić",116),
    ("expose","wystawiać na; ujawniać",117),("extend","rozszerzać",118),
    ("extent","zakres; stopień",119),("fail","nie udać się",120),
    ("feature","cecha; funkcja",121),("figure","postać; liczba",122),
    ("focus","skupiać się",123),("formal","formalny",124),("framework","ramy; struktura",125),
    ("furthermore","ponadto",126),("generate","generować",127),("goal","cel",128),
    ("handle","radzić sobie; uchwyt",129),("highlight","podkreślić; wyróżnić",130),
    ("identify","identyfikować",131),("ignore","ignorować",132),("impact","wpływ",133),
    ("implement","wdrożyć; wprowadzić",134),("imply","sugerować; implikować",135),
    ("improve","poprawić",136),("increase","zwiększyć; wzrost",137),
    ("indicate","wskazywać",138),("influence","wpływ; wpływać",139),
    ("initial","początkowy",140),("instance","przykład; przypadek",141),
    ("instead","zamiast tego",142),("interest","zainteresowanie; odsetki",143),
    ("interpret","interpretować",144),("involve","angażować; obejmować",145),
    ("issue","kwestia; problem",146),("judge","oceniać; sędzia",147),
    ("justify","uzasadniać",148),("likewise","podobnie; tak samo",149),
    ("limit","ograniczenie; limit",150),("maintain","utrzymywać",151),
    ("majority","większość",152),("manage","zarządzać; radzić sobie",153),
    ("meanwhile","w międzyczasie",154),("mention","wspominać",155),
    ("moreover","co więcej; ponadto",156),("motivation","motywacja",157),
    ("nevertheless","niemniej jednak",158),("notice","zauważyć; ogłoszenie",159),
    ("obtain","uzyskać",160),("occur","wystąpić; zdarzyć się",161),
    ("otherwise","inaczej; w przeciwnym razie",162),("outcome","wynik; rezultat",163),
    ("overcome","pokonać; przezwyciężyć",164),("particularly","szczególnie",165),
    ("pattern","wzór; schemat",166),("perceive","postrzegać",167),
    ("perform","wykonywać",168),("perspective","perspektywa",169),
    ("positive","pozytywny",170),("potential","potencjał; potencjalny",171),
    ("prefer","preferować",172),("previous","poprzedni",173),("principle","zasada",174),
    ("priority","priorytet",175),("probably","prawdopodobnie",176),
    ("promote","promować; awansować",177),("property","własność; nieruchomość",178),
    ("propose","proponować",179),("prove","udowodnić",180),("provide","zapewniać",181),
    ("pursue","dążyć; gonić",182),("purpose","cel; zamiar",183),("raise","podnieść",184),
    ("range","zakres; zasięg",185),("realize","zdać sobie sprawę",186),
    ("recent","niedawny",187),("reduce","zmniejszyć",188),("relate","odnosić się",189),
    ("relevant","istotny; trafny",190),("rely","polegać",191),("remain","pozostawać",192),
    ("replace","zastąpić",193),("represent","reprezentować",194),
    ("require","wymagać",195),("research","badania",196),("resolve","rozwiązać",197),
    ("respond","odpowiadać",198),("responsibility","odpowiedzialność",199),
    ("reveal","ujawniać",200),("role","rola",201),("satisfy","zadowalać",202),
    ("significant","znaczący; istotny",203),("similar","podobny",204),
    ("situation","sytuacja",205),("solution","rozwiązanie",206),("source","źródło",207),
    ("specific","konkretny; specyficzny",208),("sufficient","wystarczający",209),
    ("suggest","sugerować",210),("support","wspierać; wsparcie",211),
    ("survive","przeżyć",212),("target","cel; celować",213),("throughout","przez cały",214),
    ("traditional","tradycyjny",215),("transfer","przenosić; transfer",216),
    ("trend","trend; tendencja",217),("ultimately","ostatecznie",218),
    ("unique","unikalny",219),("unless","chyba że",220),("value","wartość",221),
    ("variety","różnorodność",222),("various","różny",223),("via","przez; za pomocą",224),
    ("whereas","podczas gdy; natomiast",225),("whether","czy",226),
    ("willing","chętny; skłonny",227),("withdraw","wycofać; wypłacić",228),
    ("elsewhere","gdzie indziej",229),("rarely","rzadko",230),
    ("besides","poza tym; oprócz",231),("hardly ever","prawie nigdy",232),
    ("at all","w ogóle",233),("as well","również; też",234),("so far","jak dotąd",235),
    ("for a while","przez jakiś czas",236),("in the meantime","w międzyczasie",237),
    ("at most","co najwyżej",238),("right away","od razu; natychmiast",239),
    ("somewhat","nieco; trochę",240),("associate","kojarzyć; współpracownik",241),
    ("combination","połączenie",242),("constraint","ograniczenie",243),
    ("efficient","wydajny; efektywny",244),("entire","cały; kompletny",245),
    ("environment","środowisko",246),("eventually","ostatecznie",247),
    ("factor","czynnik",248),("hence","stąd; dlatego",249),
    ("income","dochód",250),("indeed","rzeczywiście",251),
    ("option","opcja; możliwość",252),("output","wynik; produkcja",253),
    ("phase","faza; etap",254),("phrase","wyrażenie; fraza",255),
    ("prior","wcześniejszy; przed",256),("process","proces",257),
    ("sector","sektor",258),("seek","szukać; dążyć",259),
    ("select","wybrać; selekcjonować",260),("sequence","sekwencja; kolejność",261),
    ("shift","zmiana; przesunąć",262),("significant","znaczący",263),
    ("stable","stabilny",264),("strategy","strategia",265),
    ("stress","stres; podkreślać",266),("structure","struktura",267),
    ("task","zadanie",268),("technique","technika",269),
    ("term","termin; okres",270),("theory","teoria",271),
    ("toward","w kierunku",272),("trend","trend",273),
    ("valid","ważny; uzasadniony",274),("variable","zmienna; zmienny",275),
    ("version","wersja",276),("vision","wizja",277),
    ("aware","świadomy",278),("concern","obawa",279),
    ("despite","pomimo",280),("display","wyświetlać; pokaz",281),
    ("distinguish","odróżniać",282),("emphasis","nacisk",283),
    ("ensure","zapewnić",284),("expose","ujawniać",285),
    ("furthermore","ponadto",286),("guarantee","gwarancja",287),
    ("hence","dlatego",288),("imply","implikować",289),
    ("interpret","interpretować",290),("investigate","badać",291),
    ("isolation","izolacja",292),("justify","uzasadniać",293),
    ("lack","brak; brakować",294),("layer","warstwa",295),
    ("mechanism","mechanizm",296),("merely","jedynie; tylko",297),
    ("minimum","minimum",298),("mode","tryb; sposób",299),
    ("modify","modyfikować",300),("obvious","oczywisty",301),
    ("occur","wystąpić",302),("perceive","postrzegać",303),
    ("positive","pozytywny",304),("potential","potencjał",305),
    ("predict","przewidywać",306),("primary","główny; podstawowy",307),
    ("promote","promować",308),("ratio","stosunek; wskaźnik",309),
    ("reaction","reakcja",310),("recognize","rozpoznawać",311),
    ("refer","odnosić się; odwoływać",312),("regard","uważać; szacunek",313),
    ("regulate","regulować",314),("reinforce","wzmacniać",315),
    ("release","uwalniać; wydanie",316),("remove","usunąć",317),
    ("request","prośba; prosić",318),("resource","zasób",319),
    ("restrict","ograniczać",320),("retain","zachowywać; zatrzymać",321),
    ("reveal","ujawniać",322),("significant","istotny",323),
    ("status","status; stan",324),("strict","surowy; ścisły",325),
    ("subsequent","kolejny; następny",326),("sustain","podtrzymywać",327),
    ("tend","mieć tendencję",328),("trace","ślad; śledzić",329),
    ("undermine","osłabiać; podkopywać",330),("undertake","podjąć się",331),
    ("utilize","wykorzystywać",332),("virtually","praktycznie; niemal",333),
    ("widespread","powszechny",334),("yield","przynosić; ustąpić",335),
]

# ── TOP 120 najczęstszych słów wg prawdziwego rankingu COCA ──────────────────
# Ładowane z INSERT OR REPLACE — ZAWSZE mają poprawne rangi na początku kolejki
TOP_BASIC_WORDS = [
    ("the","przedimek określony (ten/ta/to w ang.)",1),
    ("be","być",2),
    ("of","z, od (partytyw)",3),
    ("and","i, oraz",4),
    ("a","przedimek nieokreślony",5),
    ("in","w, wewnątrz",6),
    ("to","do; (bezokolicznik)",7),
    ("have","mieć",8),
    ("it","to, ono",9),
    ("for","dla, za, przez",12),
    ("on","na, po",13),
    ("with","z, razem z",14),
    ("he","on",15),
    ("as","jako, jak, gdy",16),
    ("you","ty, wy",17),
    ("do","robić, czynić",18),
    ("at","przy, w",19),
    ("this","ten, ta, to (bliskie)",20),
    ("but","ale, lecz",21),
    ("his","jego",22),
    ("by","przez, koło",23),
    ("from","z, od",24),
    ("they","oni, one",25),
    ("we","my",26),
    ("say","mówić, powiedzieć",27),
    ("her","jej; ją",28),
    ("she","ona",29),
    ("or","lub, albo",30),
    ("will","będzie (przyszły czas); wola",32),
    ("my","mój, moja, moje",33),
    ("one","jeden",34),
    ("all","wszystko, wszyscy, cały",35),
    ("would","by, chciałby",36),
    ("there","tam; jest/są (there is)",37),
    ("their","ich (dzierżawczy)",38),
    ("what","co, jaki, który",39),
    ("so","więc, tak bardzo",40),
    ("up","w górę, do góry",41),
    ("out","na zewnątrz, poza",42),
    ("if","jeśli, gdyby",43),
    ("about","o, na temat, około",44),
    ("who","kto, który",45),
    ("get","dostać, zdobyć, stać się",46),
    ("which","który, które",47),
    ("go","iść, jechać",48),
    ("me","mnie, mi",49),
    ("when","kiedy, gdy",50),
    ("make","robić, tworzyć",51),
    ("can","móc, umieć",52),
    ("like","lubić; jak, podobnie jak",53),
    ("time","czas, pora",54),
    ("no","nie, żaden",55),
    ("just","właśnie, tylko, po prostu",56),
    ("him","go, jemu",57),
    ("know","wiedzieć, znać",58),
    ("take","brać, zabrać",59),
    ("people","ludzie",60),
    ("into","do (środka), w",61),
    ("year","rok",62),
    ("your","twój, wasz",63),
    ("good","dobry",64),
    ("some","jakiś, trochę, kilka",65),
    ("could","mógłby, mógłbym",66),
    ("them","ich, im, je",67),
    ("see","widzieć, zobaczyć",68),
    ("other","inny, pozostały",69),
    ("than","niż, od (porównanie)",70),
    ("then","potem, wtedy, więc",71),
    ("now","teraz, już",72),
    ("look","patrzeć, wyglądać",73),
    ("only","tylko, jedynie",74),
    ("come","przychodzić, przyjeżdżać",75),
    ("its","jego, jej (nieosobowe)",76),
    ("over","nad; ponad; przez; skończone",77),
    ("think","myśleć, uważać",78),
    ("also","też, również",79),
    ("back","z powrotem; plecy; tylny",80),
    ("after","po, za; potem",81),
    ("use","używać, stosować",82),
    ("two","dwa",83),
    ("how","jak, w jaki sposób",84),
    ("our","nasz",85),
    ("work","pracować; praca",86),
    ("first","pierwszy",87),
    ("well","dobrze; otóż",88),
    ("way","droga, sposób",89),
    ("even","nawet",90),
    ("new","nowy",91),
    ("want","chcieć",92),
    ("because","ponieważ, bo",93),
    ("any","jakiś, żaden, dowolny",94),
    ("these","te, ci (bliskie)",95),
    ("give","dawać",96),
    ("day","dzień",97),
    ("most","najbardziej; większość",98),
    ("us","nas, nam",99),
    ("great","świetny, wielki",100),
    ("between","między",101),
    ("need","potrzebować",102),
    ("large","duży, wielki",103),
    ("often","często",104),
    ("hand","ręka",105),
    ("high","wysoki",106),
    ("place","miejsce",107),
    ("hold","trzymać",108),
    ("world","świat",109),
    ("while","podczas gdy; chwila",110),
    ("life","życie",112),
    ("few","kilka, niewielu",113),
    ("open","otwarty; otworzyć",115),
    ("seem","wydawać się",116),
    ("together","razem",117),
    ("next","następny, obok",118),
    ("children","dzieci",120),
]
