import sqlite3, os
DB = os.path.join(os.path.dirname(__file__), "data", "words.db")
WORDS = [
# ── RANGI 501-800 ──
("spoke","mówił (czas przeszły speak)",501),("contain","zawierać, mieścić",502),
("speed","prędkość, przyspieszać",503),("count","liczyć, hrabia",504),
("cat","kot",505),("determine","ustalać, determinować",506),
("true","prawdziwy, wierny",507),("race","rasa, wyścig",508),
("sharp","ostry, wyraźny",509),("observe","obserwować",510),
("tube","rura, tuba",511),("necessary","konieczny, niezbędny",512),
("weight","waga, ciężar",513),("meat","mięso",514),("lift","podnosić, winda",515),
("process","proces, przetwarzać",516),("army","armia",517),
("hat","kapelusz",518),("property","własność, nieruchomość",519),
("particular","szczególny, konkretny",520),("swim","pływać",521),
("term","termin, kadencja",522),("opposite","naprzeciwko, przeciwny",523),
("wife","żona",524),("shoe","but",525),("shoulder","ramię (część ciała)",526),
("spread","rozkładać, szerzyć",527),("arrange","organizować, układać",528),
("camp","obóz, biwakować",529),("invent","wynajdować",530),
("cotton","bawełna",531),("born","urodzony",532),("determine","ustalać",533),
("quart","kwarta (jednostka)",534),("nine","dziewięć",535),
("truck","ciężarówka",536),("noise","hałas, szum",537),("level","poziom, wyrównać",538),
("chance","szansa, traf",539),("gather","zbierać, gromadzić",540),
("shop","sklep, robić zakupy",541),("stretch","rozciągać, odcinek",542),
("throw","rzucać",543),("shine","świecić, błyszczeć",544),("property","majątek",545),
("column","kolumna, rubryka",546),("molecule","cząsteczka",547),
("select","wybierać",548),("wrong","zły, błędny",549),("gray","szary",550),
("repeat","powtarzać",551),("require","wymagać",552),("broad","szeroki, obszerny",553),
("prepare","przygotowywać",554),("salt","sól",555),("nose","nos",556),
("plural","liczba mnoga",557),("anger","gniew, złość",558),("claim","twierdzić, roszczenie",559),
("continent","kontynent",560),("oxygen","tlen",561),("sugar","cukier",562),
("death","śmierć",563),("pretty","ładny, całkiem",564),("skill","umiejętność",565),
("women","kobiety (liczba mnoga woman)",566),("season","pora roku, sezon",567),
("solution","rozwiązanie, roztwór",568),("magnet","magnes",569),
("silver","srebro, srebrny",570),("thank","dziękować",571),("branch","gałąź, oddział",572),
("match","mecz, dopasowywać",573),("suffix","przyrostek",574),("especially","szczególnie",575),
("fig","figa",576),("afraid","przestraszony",577),("huge","ogromny",578),
("sister","siostra",579),("steel","stal",580),("discuss","dyskutować",581),
("forward","naprzód, przekazywać",582),("similar","podobny",583),
("guide","przewodnik, prowadzić",584),("experience","doświadczenie",585),
("score","wynik, partytura",586),("apple","jabłko",587),("bought","kupił (czas przeszły buy)",588),
("led","prowadził (czas przeszły lead)",589),("pitch","ton, boisko",590),
("coat","płaszcz, warstwa",591),("mass","masa, msza",592),
("card","karta, kartka",593),("band","zespół, opaska",594),("rope","lina",595),
("slip","poślizgnąć się, poślizg",596),("win","wygrywać",597),
("dream","sen, marzenie",598),("evening","wieczór",599),("condition","warunki, kondycja",600),
# ── RANGI 601-800 ──
("feed","karmić, kanał",601),("tool","narzędzie",602),("total","łączny, suma",603),
("basic","podstawowy",604),("smell","zapach, wąchać",605),("valley","dolina",606),
("nor","ani",607),("double","podwójny, podwoić",608),("seat","miejsce siedzące",609),
("arrive","przyjeżdżać, przybywać",610),("master","mistrz, opanować",611),
("track","ślad, tor",612),("parent","rodzic",613),("shore","brzeg, wybrzeże",614),
("division","podział",615),("sheet","prześcieradło, arkusz",616),
("substance","substancja",617),("favor","przysługa, faworyzować",618),
("connect","łączyć, podłączać",619),("post","poczta, publikować",620),
("spend","wydawać, spędzać",621),("chord","akord",622),
("fat","tłuszcz, gruby",623),("glad","zadowolony, rad",624),
("original","oryginalny, oryginał",625),("share","dzielić, akcja",626),
("station","stacja, posterunek",627),("dad","tata",628),
("bread","chleb",629),("charge","opłata, ładować",630),
("proper","właściwy, stosowny",631),("bar","bar, pręt",632),
("offer","oferta, oferować",633),("segment","segment, odcinek",634),
("slave","niewolnik",635),("duck","kaczka, uchylać się",636),
("instant","chwila, natychmiastowy",637),("market","rynek, targ",638),
("degree","stopień",639),("populate","zaludniać",640),
("chick","pisklę",641),("dear","drogi (zwrot), drogi (cenowy)",642),
("enemy","wróg",643),("reply","odpowiedź, odpowiadać",644),
("drink","pić, napój",645),("occur","zdarzać się, wystąpić",646),
("support","wsparcie, wspierać",647),("speech","mowa, przemówienie",648),
("nature","natura, przyroda",649),("range","zakres, zasięg",650),
("steam","para wodna",651),("motion","ruch, wniosek",652),
("path","ścieżka, droga",653),("liquid","płyn, ciekły",654),
("log","kłoda, dziennik",655),("meant","znaczył (czas przeszły mean)",656),
("quotient","iloraz",657),("teeth","zęby (liczba mnoga tooth)",658),
("shell","muszla, skorupa",659),("neck","szyja, kark",660),
("oxygen","tlen",661),("sugar","cukier",662),("death","śmierć",663),
("trade","handel, handlować",664),("melody","melodia",665),
("trip","podróż, wycieczka",666),("office","biuro, urząd",667),
("receive","otrzymywać",668),("row","rząd, wioślarstwo",669),
("mouth","usta, ujście",670),("exact","dokładny",671),
("symbol","symbol",672),("die","umierać",673),("least","najmniej",674),
("trouble","kłopot, trudność",675),("shout","krzyczeć, krzyk",676),
("except","z wyjątkiem, oprócz",677),("wrote","napisał (czas przeszły write)",678),
("seed","nasiono, ziarno",679),("tone","ton, odcień",680),
("join","dołączać, łączyć",681),("suggest","sugerować",682),
("clean","czysty, czyścić",683),("break","przerwa, psuć",684),
("lady","dama, pani",685),("yard","jard, podwórko",686),
("rise","wzrastać, wschód słońca",687),("bad","zły, niedobry",688),
("blow","dmuchać, uderzenie",689),("oil","olej, smarować",690),
("blood","krew",691),("touch","dotykać, dotyk",692),
("grew","rósł (czas przeszły grow)",693),("cent","cent",694),
("mix","mieszać, mieszanina",695),("team","drużyna, zespół",696),
("wire","drut, przewód",697),("cost","kosztować, koszt",698),
("lost","zgubiony, stracony",699),("brown","brązowy",700),
("wear","nosić (ubranie), zużycie",701),("garden","ogród",702),
("equal","równy, równać się",703),("sent","wysłał (czas przeszły send)",704),
("choose","wybierać",705),("fell","upadł (czas przeszły fall)",706),
("fit","pasować, sprawny",707),("flow","płynąć, przepływ",708),
("fair","targi, uczciwy",709),("bank","bank, brzeg rzeki",710),
("collect","zbierać, kolekcjonować",711),("save","oszczędzać, ratować",712),
("control","kontrola, kontrolować",713),("decimal","dziesiętny",714),
("gentle","łagodny, delikatny",715),("woman","kobieta",716),
("captain","kapitan",717),("practice","praktyka, ćwiczenie",718),
("separate","oddzielać, oddzielny",719),("please","proszę, sprawić przyjemność",720),
("protect","chronić",721),("noon","południe (godzina)",722),
("whose","czyj, którego",723),("locate","lokalizować",724),
("ring","pierścień, dzwonić",725),("character","charakter, postać",726),
("insect","owad",727),("caught","złapał (czas przeszły catch)",728),
("period","okres, czas",729),("indicate","wskazywać",730),
("age","wiek, epoka",731),("food","jedzenie, pożywienie",732),
("between","między, pośrodku",733),("own","własny, posiadać",734),
("below","poniżej, pod",735),("country","kraj, wieś",736),
("plant","roślina, sadzić",737),("last","ostatni, trwać",738),
("school","szkoła",739),("father","ojciec",740),
("keep","trzymać, zachowywać",741),("tree","drzewo",742),
("never","nigdy",743),("start","zaczynać, start",744),
("city","miasto",745),("earth","ziemia, gleba",746),
("eye","oko",747),("light","światło, jasny",748),
("thought","myśl, myślał",749),("head","głowa, kierownik",750),
("under","pod, poniżej",751),("story","historia, opowiadanie",752),
("saw","zobaczył (czas przeszły see), piła",753),("left","lewy, opuścił",754),
("don't","nie rób (skrót do not)",755),("few","kilka, niewielu",756),
("while","podczas gdy, chwila",757),("along","wzdłuż, razem",758),
("might","mógłby (tryb warunkowy), moc",759),("close","blisko, zamykać",760),
("something","coś",761),("seem","wydawać się",762),
("side","strona, bok",763),("been","był (imiesłów be)",764),
("really","naprawdę, rzeczywiście",765),("call","dzwonić, nazywać",766),
("that's","to jest (skrót)",767),("long","długi, długo",768),
("here","tutaj",769),("put","kłaść, umieszczać",770),
("end","koniec, kończyć",771),("does","robi (trzecia osoba)",772),
("large","duży, wielki",773),("big","duży, wielki",774),
("down","w dół, dół",775),("move","ruszać, przeprowadzka",776),
("turn","obracać, zakręt",777),("face","twarz, twarzą w twarz",778),
("thing","rzecz, sprawa",779),("tell","mówić, powiedzieć",780),
("much","dużo, bardzo",781),("before","przed, zanim",782),
("line","linia, wiersz",783),("right","prawy, prawo, słuszny",784),
("too","za bardzo, też",785),("mean","znaczyć, okrutny",786),
("old","stary, dawny",787),("any","jakikolwiek, żaden",788),
("same","ten sam, taki sam",795),("tell","mówić, opowiadać",796),
("boy","chłopiec",797),("follow","śledzić, podążać",798),
("came","przyszedł (czas przeszły come)",799),("want","chcieć",800),
]
conn = sqlite3.connect(DB)
conn.executemany("INSERT OR REPLACE INTO coca_words (word,translation,frequency_rank) VALUES (?,?,?)", WORDS)
conn.commit()
print(f"Czesc 3 OK: {len(WORDS)} slow (rangi 501-800), zmienionych: {conn.execute('SELECT changes()').fetchone()[0]}")
conn.close()
