import sqlite3, os
DB = os.path.join(os.path.dirname(__file__), "data", "words.db")
WORDS = [
# ── RANGI 251-500 ──
("plan","plan, planować",251),("figure","postać, figura, rozumieć",252),
("star","gwiazda, gwiazdor",253),("box","pudełko, boks",254),("noun","rzeczownik",255),
("field","pole, dziedzina",256),("rest","odpoczynek, reszta",257),("correct","poprawny, korygować",258),
("able","zdolny, umieć",259),("pound","funt, bić",260),("done","zrobiony, gotowe",261),
("beauty","piękno, uroda",262),("drive","jazda, dążenie",263),("stood","stał (czas przeszły stand)",264),
("contain","zawierać",265),("front","przód, czoło",266),("teach","uczyć, nauczać",267),
("week","tydzień",268),("final","końcowy, finał",269),("gave","dał (czas przeszły give)",270),
("green","zielony",271),("oh","och, ach",272),("quick","szybki, prędki",273),
("develop","rozwijać, opracowywać",274),("ocean","ocean",275),("warm","ciepły, ogrzewać",276),
("free","wolny, bezpłatny",277),("minute","minuta, chwila",278),("strong","silny, mocny",279),
("special","specjalny, wyjątkowy",280),("mind","umysł, myśleć",281),("behind","za, z tyłu",282),
("clear","jasny, czysty",283),("tail","ogon",284),("produce","wytwarzać, produkt",285),
("fact","fakt",286),("street","ulica",287),("inch","cal (jednostka)",288),
("lot","dużo, działka",289),("nothing","nic",290),("course","kurs, oczywiście",291),
("stay","zostać, pobyt",292),("wheel","koło, kierownica",293),("full","pełny, cały",294),
("force","siła, zmuszać",295),("blue","niebieski",296),("object","przedmiot, sprzeciwić się",297),
("decide","decydować",298),("surface","powierzchnia",299),("deep","głęboki, głęboko",300),
("moon","księżyc",301),("island","wyspa",302),("foot","stopa, noga",303),
("system","system, układ",304),("busy","zajęty, ruchliwy",305),("test","test, sprawdzian",306),
("record","rekord, nagrywać",307),("boat","łódź, statek",308),("common","wspólny, zwykły",309),
("gold","złoto, złoty",310),("possible","możliwy",311),("plane","samolot, równina",312),
("age","wiek, starzenie",313),("dry","suchy, suszyć",314),("wonder","zastanawiać się, cud",315),
("laugh","śmiać się, śmiech",316),("thousand","tysiąc",317),("ago","temu (przeszłość)",318),
("ran","biegł (czas przeszły run)",319),("check","sprawdzać, czek",320),
("game","gra, mecz",321),("shape","kształt, tworzyć",322),("equate","przyrównywać",323),
("hot","gorący",324),("miss","tęsknić, miss",325),("brought","przyniósł (czas przeszły bring)",326),
("heat","ciepło, ogrzewać",327),("snow","śnieg, padać śniegiem",328),
("tire","opona, męczyć",329),("bring","przynosić, przywozić",330),
("yes","tak",331),("distant","odległy, daleki",332),("fill","wypełniać",333),
("east","wschód",334),("paint","malować, farba",335),("language","język",336),
("among","wśród, między",337),("grand","wspaniały, gran",338),("ball","piłka, bal",339),
("yet","jeszcze, jednak",340),("wave","fala, machać",341),("drop","kropla, upuścić",342),
("heart","serce",343),("am","jestem (czasownik być)",344),("present","obecny, prezent",345),
("heavy","ciężki",346),("dance","taniec, tańczyć",347),("engine","silnik",348),
("position","pozycja, stanowisko",349),("arm","ramię, broń",350),
("wide","szeroki, szeroko",351),("sail","żagiel, żeglować",352),("material","materiał",353),
("fraction","ułamek, część",354),("forest","las",355),("sit","siedzieć",356),
("race","wyścig, rasa",357),("window","okno",358),("store","sklep, przechowywać",359),
("summer","lato",360),("train","pociąg, trenować",361),("sleep","spać, sen",362),
("prove","udowadniać",363),("lone","samotny, jedyny",364),("leg","noga, etap",365),
("exercise","ćwiczenie, ćwiczyć",366),("wall","ściana, mur",367),("catch","łapać",368),
("mount","wspinać się, góra",369),("wish","życzenie, życzyć",370),
("sky","niebo",371),("board","deska, zarząd",372),("joy","radość",373),
("winter","zima",374),("sat","siedział (czas przeszły sit)",375),("written","napisany",376),
("wild","dziki",377),("instrument","instrument, narzędzie",378),("kept","trzymał (czas przeszły keep)",379),
("glass","szkło, szklanka",380),("grass","trawa",381),("cow","krowa",382),
("job","praca, zajęcie",383),("edge","krawędź, przewaga",384),("sign","znak, podpisywać",385),
("visit","odwiedzać, wizyta",386),("past","przeszłość, obok",387),("soft","miękki",388),
("fun","zabawa, przyjemność",389),("bright","jasny, bystry",390),("gas","gaz, benzyna",391),
("weather","pogoda",392),("month","miesiąc",393),("million","milion",394),
("bear","niedźwiedź, znosić",395),("finish","kończyć, meta",396),("happy","szczęśliwy",397),
("hope","nadzieja, mieć nadzieję",398),("flower","kwiat",399),("clothe","ubierać",400),
("strange","dziwny",401),("gone","zniknął, odszedł",402),("jump","skakać, skok",403),
("baby","niemowlę, dziecko",404),("eight","osiem",405),("village","wieś, wioska",406),
("meet","spotykać",407),("root","korzeń",408),("buy","kupować",409),
("raise","podnosić, hodować",410),("solve","rozwiązywać",411),("metal","metal",412),
("whether","czy (pytanie pośrednie)",413),("push","pchać, naciskać",414),("seven","siedem",415),
("paragraph","akapitt",416),("third","trzeci",417),("shall","będzie (forma modalna)",418),
("held","trzymał (czas przeszły hold)",419),("hair","włosy",420),
("describe","opisywać",421),("cook","gotować, kucharz",422),("floor","podłoga, piętro",423),
("either","albo...albo, żaden z dwóch",424),("result","wynik, rezultat",425),
("burn","palić się, spalać",426),("hill","wzgórze",427),("safe","bezpieczny, sejf",428),
("cat","kot",429),("century","stulecie, wiek",430),("consider","rozważać, uważać za",431),
("type","typ, pisać na klawiaturze",432),("law","prawo, ustawa",433),
("bit","kawałek, trochę",434),("coast","wybrzeże",435),("copy","kopia, kopiować",436),
("phrase","fraza, zwrot",437),("silent","cichy, milczący",438),("tall","wysoki (o osobach)",439),
("sand","piasek",440),("soil","gleba, ziemia",441),("roll","toczyć, rolka",442),
("temperature","temperatura",443),("finger","palec",444),("industry","przemysł",445),
("value","wartość, cenić",446),("fight","walczyć, bić się",447),("lie","kłamać, leżeć",448),
("beat","bić, pokonać",449),("excite","ekscytować",450),
("natural","naturalny",451),("view","widok, pogląd",452),("sense","sens, zmysł",453),
("capital","kapitał, stolica",454),("won't","nie będzie (skrót)",455),
("chair","krzesło",456),("danger","niebezpieczeństwo",457),("fruit","owoc",458),
("rich","bogaty",459),("thick","gruby (o obiektach)",460),("soldier","żołnierz",461),
("process","proces, przetwarzać",462),("operate","działać, operować",463),
("practice","praktyka, ćwiczyć",464),("separate","oddzielny, oddzielać",465),
("difficult","trudny",466),("doctor","lekarz",467),("please","proszę, zadowalać",468),
("protect","chronić, zabezpieczać",469),("noon","południe (godzina 12)",470),
("whose","czyj, którego",471),("locate","umieszczać, znajdować",472),
("ring","pierścień, dzwonić",473),("character","postać, charakter",474),
("insect","owad",475),("caught","złapał (czas przeszły catch)",476),
("period","okres, kropka",477),("indicate","wskazywać, oznaczać",478),
("radio","radio",479),("spoke","mówił (czas przeszły speak)",480),
("atom","atom",481),("human","człowiek, ludzki",482),("history","historia",483),
("effect","efekt, skutek",484),("electric","elektryczny",485),("expect","oczekiwać",486),
("crop","plon, uprawa",487),("modern","nowoczesny, współczesny",488),
("element","element, żywioł",489),("hit","uderzać, trafić",490),
("student","student, uczeń",491),("corner","róg, kąt",492),("party","przyjęcie, partia",493),
("supply","dostarczać, zapasy",494),("bone","kość",495),("rail","szyna, poręcz",496),
("imagine","wyobrażać sobie",497),("provide","zapewniać, dostarczać",498),
("agree","zgadzać się",499),("thus","więc, zatem",500),
]
conn = sqlite3.connect(DB)
conn.executemany("INSERT OR REPLACE INTO coca_words (word,translation,frequency_rank) VALUES (?,?,?)", WORDS)
conn.commit()
print(f"Czesc 2 OK: {len(WORDS)} slow (rangi 251-500), zmienionych: {conn.execute('SELECT changes()').fetchone()[0]}")
conn.close()
