import sqlite3, os
DB = os.path.join(os.path.dirname(__file__), "data", "words.db")

# INSERT OR REPLACE - bezpieczne dla danych uzytkownikow (tabela words nie jest dotykana)
# Naprawia ranki i uzupelnia luki az do ~3000 slow
WORDS = [
# ── RANGI 1-120 (juz sa, ale INSERT OR REPLACE naprawi rangi) ──
("the","ten, ta, to (rodzajnik)",1),("be","być",2),("of","z, od",3),("and","i, oraz",4),
("a","pewien, jakiś (rodzajnik)",5),("in","w, na, do",6),("to","do, aby",7),("have","mieć",8),
("it","to, ono",9),("for","dla, za",10),("not","nie",11),("on","na, przy",12),
("with","z, razem z",13),("he","on",14),("as","jako, jak",15),("you","ty, wy",16),
("do","robić, czynić",17),("at","przy, w",18),("this","ten, ta, to",19),("but","ale, lecz",20),
("his","jego",21),("by","przez, przy",22),("from","z, od",23),("they","oni, one",24),
("we","my",25),("say","mówić, powiedzieć",26),("her","jej, ją",27),("she","ona",28),
("or","lub, albo",29),("an","pewien (rodzajnik)",30),("will","będzie (przyszłość)",31),
("my","mój, moja, moje",32),("one","jeden, pewien",33),("all","wszystko, wszyscy",34),
("would","chciałby (tryb warunkowy)",35),("there","tam",36),("their","ich",37),
("what","co, jaki",38),("so","więc, tak",39),("up","w górę, do góry",40),
("out","na zewnątrz, poza",41),("if","jeśli, jeżeli",42),("about","o, około",43),
("who","kto, który",44),("get","dostać, zdobyć",45),("which","który, jaki",46),
("go","iść, jechać",47),("me","mnie, mi",48),("when","kiedy, gdy",49),
("make","robić, tworzyć",50),("can","móc, umieć",51),("like","lubić, jak",52),
("time","czas, pora",53),("no","nie, żaden",54),("just","właśnie, tylko",55),
("him","go, jemu",56),("know","wiedzieć, znać",57),("take","brać, wziąć",58),
("people","ludzie",59),("into","do (środka), w",60),("year","rok",61),
("your","twój, wasz",62),("good","dobry",63),("some","kilka, trochę",64),
("could","mógłby (tryb warunkowy)",65),("them","ich, je, im",66),("see","widzieć, zobaczyć",67),
("other","inny, pozostały",68),("than","niż, od (porównanie)",69),("then","wtedy, następnie",70),
("now","teraz, już",71),("look","patrzeć, wyglądać",72),("only","tylko, jedyny",73),
("come","przychodzić, przyjechać",74),("its","jego (rodzaj nijaki)",75),
("over","nad, ponad, skończone",76),("think","myśleć, sądzić",77),("also","również, także",78),
("back","z powrotem, tył",79),("after","po, za, potem",80),("use","używać, zastosowanie",81),
("two","dwa",82),("how","jak, w jaki sposób",83),("our","nasz, nasza, nasze",84),
("work","praca, pracować",85),("first","pierwszy, najpierw",86),("well","dobrze, no cóż",87),
("way","droga, sposób",88),("even","nawet, równy",89),("new","nowy",90),
("want","chcieć, pragnienie",91),("because","ponieważ, bo",92),("any","jakikolwiek, żaden",93),
("these","te, ci (bliskie)",94),("give","dawać, dać",95),("day","dzień",96),
("most","najbardziej, większość",97),("us","nas, nam",98),("between","między, pomiędzy",99),
("need","potrzebować, potrzeba",100),("great","świetny, wielki",101),
("large","duży, wielki",102),("often","często",103),("hand","ręka, dłoń",104),
("high","wysoki, wysoko",105),("place","miejsce, umieszczać",106),("hold","trzymać, organizować",107),
("world","świat",108),("while","podczas gdy, chwila",109),("life","życie",110),
("few","kilka, mało",111),("north","północ",112),("open","otwierać, otwarty",113),
("seem","wydawać się",114),("together","razem",115),("next","następny, obok",116),
("white","biały, biel",117),("children","dzieci",118),("begin","zaczynać, rozpoczynać",119),
("got","dostał, miał (czas przeszły get)",120),
# ── BRAKUJACE RANGI 121-172 ──
("walk","chodzić, spacer",121),("example","przykład",122),("ease","łatwość, ulżyć",123),
("paper","papier, gazeta",124),("group","grupa, grupować",125),("always","zawsze",126),
("music","muzyka",127),("those","tamte, tamci",128),("both","oboje, oba",129),
("mark","znak, zaznaczyć",130),("book","książka",131),("letter","list, litera",132),
("until","dopóki, aż",133),("mile","mila",134),("river","rzeka",135),
("car","samochód",136),("feet","stopy (liczba mnoga foot)",137),("care","troska, dbać",138),
("second","drugi, sekunda",139),("enough","wystarczający, dość",140),
("plain","prosty, równina",141),("girl","dziewczyna, dziewczynka",142),
("usual","zwykły, normalny",143),("young","młody",144),("ready","gotowy",145),
("above","powyżej, nad",146),("ever","kiedykolwiek, zawsze",147),("red","czerwony",148),
("list","lista",149),("though","chociaż, jednak",150),("feel","czuć, dotykać",151),
("talk","rozmawiać, rozmowa",152),("bird","ptak",153),("soon","wkrótce, niedługo",154),
("body","ciało, korpus",155),("dog","pies",156),("family","rodzina",157),
("direct","bezpośredni, kierować",158),("pose","pozować, stwarzać",159),
("leave","opuszczać, zostawiać",160),("song","piosenka",161),("measure","mierzyć, miara",162),
("door","drzwi",163),("product","produkt",164),("black","czarny",165),
("short","krótki, niski",166),("numeral","liczba, cyfra",167),("class","klasa, zajęcia",168),
("wind","wiatr",169),("question","pytanie, kwestionować",170),("happen","zdarzać się, dziać się",171),
("complete","kompletny, ukończyć",172),
# ── RANGI 173-250 ──
("ship","statek, wysyłać",173),("area","obszar, teren",174),("half","połowa, pół",175),
("rock","skała, muzyka rockowa",176),("order","zamówić, porządek",177),
("fire","ogień, strzelać",178),("south","południe",179),("problem","problem, kłopot",180),
("piece","kawałek, utwór",181),("told","powiedział (czas przeszły tell)",182),
("knew","wiedział (czas przeszły know)",183),("pass","przejść, podać",184),
("since","od, ponieważ",185),("top","wierzch, szczyt",186),("whole","cały, kompletny",187),
("king","król",188),("space","przestrzeń, kosmos",189),("heard","słyszał (czas przeszły hear)",190),
("best","najlepszy",191),("hour","godzina",192),("better","lepszy, lepiej",193),
("true","prawdziwy, naprawdę",194),("during","podczas, w trakcie",195),
("hundred","sto, setka",196),("five","pięć",197),("remember","pamiętać",198),
("step","krok, stopień",199),("early","wczesny, wcześnie",200),
("hold","trzymać, posiadać",201),("west","zachód",202),("ground","ziemia, grunt",203),
("interest","zainteresowanie, odsetki",204),("reach","sięgać, osiągać",205),
("fast","szybki, pościć",206),("verb","czasownik",207),("sing","śpiewać",208),
("listen","słuchać",209),("six","sześć",210),("table","stół, tabela",211),
("travel","podróżować, podróż",212),("less","mniej, mniejszy",213),
("morning","ranek, rano",214),("ten","dziesięć",215),("simple","prosty, łatwy",216),
("several","kilka, kilkoro",217),("vowel","samogłoska",218),("toward","w kierunku",219),
("war","wojna",220),("lay","kłaść, leżeć",221),("against","przeciwko, przy",222),
("pattern","wzór, wzorzec",223),("slow","wolny, zwolnić",224),("center","centrum, środek",225),
("love","miłość, kochać",226),("person","osoba",227),("money","pieniądze",228),
("serve","służyć, obsługiwać",229),("appear","pojawiać się, wydawać się",230),
("road","droga, szosa",231),("map","mapa",232),("rain","deszcz, padać",233),
("rule","zasada, rządzić",234),("govern","rządzić",235),("pull","ciągnąć, wciągać",236),
("cold","zimny, przeziębienie",237),("notice","zauważać, ogłoszenie",238),
("voice","głos",239),("unit","jednostka",240),("power","moc, władza",241),
("town","miasto (mniejsze)",242),("fine","grzywna, świetny",243),("drive","prowadzić, dążyć",244),
("lead","prowadzić, ołów",245),("cry","płakać, krzyczeć",246),("dark","ciemny, ciemność",247),
("machine","maszyna",248),("note","notatka, zauważać",249),("wait","czekać",250),
]
print(f"Czesc 1: {len(WORDS)} slow przygotowanych")

conn = sqlite3.connect(DB)
conn.executemany("INSERT OR REPLACE INTO coca_words (word,translation,frequency_rank) VALUES (?,?,?)", WORDS)
conn.commit()
print(f"Wstawiono/zaktualizowano {conn.execute('SELECT changes()').fetchone()[0]} rekordow (czesc 1)")
conn.close()
